### ISSUE TITLE
Evaluating subsetting conditions in long data

### ISSUE THREAD

**Issue by andkov** [IALSA/wave-inclusion#15]
Given a dataset 
```
(ds <- data.frame(
  id           = c(111,111,111,222,222,222, 333, 333),
  wave         = c(0, 1, 2, 0, 1, 2, 0, 1),
  dementia = c(0, 0, 1, 0, 0, NA, 0, 0)
))

   id wave dementia
1 111    0        0
2 111    1        0
3 111    2        1
4 222    0        0
5 222    1        0
6 222    2       NA
7 333    0        0
8 333    1        0
```

I would like to develop a rule with `dplyr` idioms that would excluded those persons, for which `dementia == 1` is true at any time point. My strategy is to use `group_by` to make evaluation of `dementia` of each person, which i can later use to exclude observations from the data set. However, i'm having difficulty expressing this rule as single `dplyr` call. Here's how it's done now: 
```
keep_ids <- ds %>% 
  dplyr::filter(dementia == 1) %>%
  dplyr::mutate( exclude = 1) %>%
  dplyr::select(id)
(keep_ids <- as.numeric(keep_ids$id))

(d <- ds[!ds$id %in% keep_ids,])

   id wave dementia
4 222    0        0
5 222    1        0
6 222    2       NA
```
It should be something simple and elegant, but my imagination blanks out on `dplyr`, which is a bit unnerving, because I have a strong suspicion that I already figured out how to accomplish this task at some point (but can't find it). Could please give me a hint, @wibeasley ?

**Comment by wibeasley** [comment]
First group, then call `any()` inside mutate (not summarize).  Last ungroup.

**Comment by andkov** [comment]
thanks, @wibeasley , that did the trick. 
```
ds %>% dplyr::group_by(id) %>%
  dplyr::mutate(dementia_ever = any(dementia==1)) %>%
  dplyr::ungroup()

Source: local data frame [8 x 4]

     id  wave dementia dementia_ever
  (dbl) (dbl)    (dbl)         (lgl)
1   111     0        0          TRUE
2   111     1        0          TRUE
3   111     2        1          TRUE
4   222     0        0            NA
5   222     1        0            NA
6   222     2       NA            NA
7   333     0        0          TRUE
8   333     1        1          TRUE
```

First I thought i wanted `dementia_ever` resolve to `FALSE` when `NA` is present in any of the values, but on second thought, it seems more diligent to include into the condition specification instead:

```
ds %>% dplyr::group_by(id) %>%
  dplyr::mutate(dementia_ever = any(dementia==1)) %>%
  dplyr::ungroup() %>%
  dplyr::filter(dementia_ever %in% c(FALSE, NA))

Source: local data frame [3 x 4]

     id  wave dementia dementia_ever
  (dbl) (dbl)    (dbl)         (lgl)
1   222     0        0            NA
2   222     1        0            NA
3   222     2       NA            NA
```

see the record in the [thesaurus.R](https://github.com/IALSA/wave-inclusion/blob/master/scripts/thesaurus.R)

**Comment by wibeasley** [comment]
I don't think that `%in%` will work with NA.  You'll probably  need to use in.na().
